const fs = require('fs')
const path = require('path')

const updates = {
  'driver-schumacher-2002': {
    racePace: 99,
    qualifyingPace: 97,
    consistency: 99,
    wetSkill: 94,
    tireManagement: 96,
    overtaking: 94,
    defending: 94,
    adaptability: 96,
    technicalFeedback: 99,
    pressureHandling: 98,
    aggression: 88,
    teamPlay: 82,
    errorProneness: 8,
    incidentRisk: 12,
    politicalTension: 30,
    budgetCost: 230,
  },
  'driver-senna-1988': {
    racePace: 98,
    qualifyingPace: 100,
    consistency: 90,
    wetSkill: 99,
    tireManagement: 88,
    overtaking: 97,
    defending: 94,
    adaptability: 96,
    technicalFeedback: 93,
    pressureHandling: 99,
    aggression: 96,
    teamPlay: 70,
    errorProneness: 16,
    incidentRisk: 22,
    politicalTension: 45,
    budgetCost: 225,
  },
  'driver-senna-1991': {
    racePace: 99,
    qualifyingPace: 100,
    consistency: 94,
    wetSkill: 100,
    tireManagement: 90,
    overtaking: 97,
    defending: 95,
    adaptability: 97,
    technicalFeedback: 94,
    pressureHandling: 99,
    aggression: 94,
    teamPlay: 74,
    errorProneness: 12,
    incidentRisk: 18,
    politicalTension: 40,
    budgetCost: 230,
  },
  'driver-prost-1986': {
    racePace: 98,
    qualifyingPace: 92,
    consistency: 99,
    wetSkill: 84,
    tireManagement: 98,
    overtaking: 88,
    defending: 92,
    adaptability: 95,
    technicalFeedback: 97,
    pressureHandling: 98,
    aggression: 68,
    teamPlay: 78,
    errorProneness: 5,
    incidentRisk: 8,
    politicalTension: 42,
    budgetCost: 218,
  },
  'driver-prost-1993': {
    racePace: 96,
    qualifyingPace: 91,
    consistency: 98,
    wetSkill: 78,
    tireManagement: 98,
    overtaking: 84,
    defending: 90,
    adaptability: 93,
    technicalFeedback: 96,
    pressureHandling: 97,
    aggression: 62,
    teamPlay: 80,
    errorProneness: 5,
    incidentRisk: 7,
    politicalTension: 35,
    budgetCost: 205,
  },
  'driver-schumacher-1995': {
    racePace: 99,
    qualifyingPace: 96,
    consistency: 96,
    wetSkill: 96,
    tireManagement: 93,
    overtaking: 96,
    defending: 94,
    adaptability: 99,
    technicalFeedback: 98,
    pressureHandling: 98,
    aggression: 92,
    teamPlay: 76,
    errorProneness: 12,
    incidentRisk: 18,
    politicalTension: 38,
    budgetCost: 225,
  },
  'driver-hamilton-2020': {
    racePace: 99,
    qualifyingPace: 98,
    consistency: 99,
    wetSkill: 96,
    tireManagement: 98,
    overtaking: 96,
    defending: 94,
    adaptability: 96,
    technicalFeedback: 94,
    pressureHandling: 99,
    aggression: 84,
    teamPlay: 86,
    errorProneness: 6,
    incidentRisk: 9,
    politicalTension: 20,
    budgetCost: 228,
  },
  'driver-hamilton-2008': {
    racePace: 96,
    qualifyingPace: 98,
    consistency: 88,
    wetSkill: 98,
    tireManagement: 88,
    overtaking: 98,
    defending: 92,
    adaptability: 94,
    technicalFeedback: 88,
    pressureHandling: 92,
    aggression: 95,
    teamPlay: 72,
    errorProneness: 18,
    incidentRisk: 24,
    politicalTension: 35,
    budgetCost: 210,
  },
  'driver-verstappen-2023': {
    racePace: 99,
    qualifyingPace: 98,
    consistency: 99,
    wetSkill: 95,
    tireManagement: 96,
    overtaking: 98,
    defending: 96,
    adaptability: 96,
    technicalFeedback: 94,
    pressureHandling: 99,
    aggression: 93,
    teamPlay: 78,
    errorProneness: 7,
    incidentRisk: 13,
    politicalTension: 28,
    budgetCost: 228,
  },
  'driver-verstappen-2021': {
    racePace: 98,
    qualifyingPace: 98,
    consistency: 94,
    wetSkill: 94,
    tireManagement: 93,
    overtaking: 98,
    defending: 97,
    adaptability: 95,
    technicalFeedback: 92,
    pressureHandling: 97,
    aggression: 97,
    teamPlay: 72,
    errorProneness: 12,
    incidentRisk: 22,
    politicalTension: 38,
    budgetCost: 218,
  },
  'driver-alonso-2006': {
    racePace: 98,
    qualifyingPace: 95,
    consistency: 97,
    wetSkill: 91,
    tireManagement: 96,
    overtaking: 94,
    defending: 96,
    adaptability: 97,
    technicalFeedback: 98,
    pressureHandling: 97,
    aggression: 86,
    teamPlay: 76,
    errorProneness: 8,
    incidentRisk: 12,
    politicalTension: 35,
    budgetCost: 215,
  },
  'driver-alonso-2012': {
    racePace: 99,
    qualifyingPace: 95,
    consistency: 98,
    wetSkill: 94,
    tireManagement: 97,
    overtaking: 96,
    defending: 98,
    adaptability: 100,
    technicalFeedback: 98,
    pressureHandling: 99,
    aggression: 88,
    teamPlay: 74,
    errorProneness: 6,
    incidentRisk: 10,
    politicalTension: 42,
    budgetCost: 222,
  },
  'driver-fangio-1957': {
    racePace: 98,
    qualifyingPace: 96,
    consistency: 96,
    wetSkill: 88,
    tireManagement: 95,
    overtaking: 92,
    defending: 92,
    adaptability: 98,
    technicalFeedback: 94,
    pressureHandling: 99,
    aggression: 78,
    teamPlay: 85,
    errorProneness: 7,
    incidentRisk: 12,
    politicalTension: 18,
    budgetCost: 215,
  },
  'driver-clark-1965': {
    racePace: 99,
    qualifyingPace: 99,
    consistency: 96,
    wetSkill: 94,
    tireManagement: 94,
    overtaking: 94,
    defending: 92,
    adaptability: 97,
    technicalFeedback: 95,
    pressureHandling: 97,
    aggression: 82,
    teamPlay: 84,
    errorProneness: 8,
    incidentRisk: 12,
    politicalTension: 15,
    budgetCost: 220,
  },
  'driver-vettel-2011': {
    racePace: 96,
    qualifyingPace: 99,
    consistency: 95,
    wetSkill: 88,
    tireManagement: 92,
    overtaking: 88,
    defending: 90,
    adaptability: 90,
    technicalFeedback: 93,
    pressureHandling: 95,
    aggression: 82,
    teamPlay: 82,
    errorProneness: 10,
    incidentRisk: 14,
    politicalTension: 22,
    budgetCost: 205,
  },
  'driver-lauda-1977': {
    racePace: 95,
    qualifyingPace: 90,
    consistency: 99,
    wetSkill: 84,
    tireManagement: 98,
    overtaking: 86,
    defending: 92,
    adaptability: 96,
    technicalFeedback: 99,
    pressureHandling: 99,
    aggression: 65,
    teamPlay: 88,
    errorProneness: 4,
    incidentRisk: 7,
    politicalTension: 22,
    budgetCost: 200,
  },
  'driver-mansell-1992': {
    racePace: 98,
    qualifyingPace: 97,
    consistency: 89,
    wetSkill: 84,
    tireManagement: 88,
    overtaking: 97,
    defending: 90,
    adaptability: 90,
    technicalFeedback: 88,
    pressureHandling: 92,
    aggression: 96,
    teamPlay: 70,
    errorProneness: 18,
    incidentRisk: 24,
    politicalTension: 40,
    budgetCost: 198,
  },
  'driver-hakkinen-1998': {
    racePace: 96,
    qualifyingPace: 98,
    consistency: 93,
    wetSkill: 82,
    tireManagement: 90,
    overtaking: 92,
    defending: 90,
    adaptability: 91,
    technicalFeedback: 90,
    pressureHandling: 96,
    aggression: 80,
    teamPlay: 84,
    errorProneness: 10,
    incidentRisk: 13,
    politicalTension: 15,
    budgetCost: 195,
  },
  'driver-raikkonen-2005': {
    racePace: 99,
    qualifyingPace: 97,
    consistency: 91,
    wetSkill: 88,
    tireManagement: 92,
    overtaking: 95,
    defending: 92,
    adaptability: 93,
    technicalFeedback: 88,
    pressureHandling: 95,
    aggression: 84,
    teamPlay: 80,
    errorProneness: 11,
    incidentRisk: 16,
    politicalTension: 12,
    budgetCost: 205,
  },
  'driver-piquet-1983': {
    racePace: 95,
    qualifyingPace: 94,
    consistency: 94,
    wetSkill: 82,
    tireManagement: 94,
    overtaking: 90,
    defending: 92,
    adaptability: 95,
    technicalFeedback: 97,
    pressureHandling: 96,
    aggression: 78,
    teamPlay: 72,
    errorProneness: 9,
    incidentRisk: 13,
    politicalTension: 38,
    budgetCost: 190,
  },
  'driver-leclerc-2022': {
    racePace: 94,
    qualifyingPace: 99,
    consistency: 84,
    wetSkill: 84,
    tireManagement: 86,
    overtaking: 92,
    defending: 88,
    adaptability: 90,
    technicalFeedback: 88,
    pressureHandling: 88,
    aggression: 86,
    teamPlay: 82,
    errorProneness: 18,
    incidentRisk: 20,
    politicalTension: 18,
    budgetCost: 180,
  },
  'driver-rosberg-2016': {
    racePace: 93,
    qualifyingPace: 95,
    consistency: 96,
    wetSkill: 78,
    tireManagement: 94,
    overtaking: 86,
    defending: 90,
    adaptability: 90,
    technicalFeedback: 92,
    pressureHandling: 96,
    aggression: 76,
    teamPlay: 70,
    errorProneness: 7,
    incidentRisk: 10,
    politicalTension: 45,
    budgetCost: 185,
  },
  'driver-ricciardo-2014': {
    racePace: 95,
    qualifyingPace: 92,
    consistency: 94,
    wetSkill: 88,
    tireManagement: 94,
    overtaking: 98,
    defending: 91,
    adaptability: 94,
    technicalFeedback: 90,
    pressureHandling: 95,
    aggression: 86,
    teamPlay: 88,
    errorProneness: 8,
    incidentRisk: 12,
    politicalTension: 12,
    budgetCost: 188,
  },
  'driver-massa-2008': {
    racePace: 93,
    qualifyingPace: 95,
    consistency: 89,
    wetSkill: 68,
    tireManagement: 88,
    overtaking: 88,
    defending: 86,
    adaptability: 86,
    technicalFeedback: 88,
    pressureHandling: 87,
    aggression: 78,
    teamPlay: 86,
    errorProneness: 12,
    incidentRisk: 16,
    politicalTension: 12,
    budgetCost: 165,
  },
  'driver-norris-2024': {
    racePace: 95,
    qualifyingPace: 95,
    consistency: 93,
    wetSkill: 88,
    tireManagement: 92,
    overtaking: 92,
    defending: 88,
    adaptability: 92,
    technicalFeedback: 88,
    pressureHandling: 88,
    aggression: 82,
    teamPlay: 88,
    errorProneness: 10,
    incidentRisk: 13,
    politicalTension: 8,
    budgetCost: 180,
  },
  'driver-button-2009': {
    racePace: 92,
    qualifyingPace: 90,
    consistency: 96,
    wetSkill: 94,
    tireManagement: 98,
    overtaking: 86,
    defending: 88,
    adaptability: 92,
    technicalFeedback: 92,
    pressureHandling: 94,
    aggression: 65,
    teamPlay: 90,
    errorProneness: 5,
    incidentRisk: 8,
    politicalTension: 8,
    budgetCost: 175,
  },
  'driver-webber-2010': {
    racePace: 91,
    qualifyingPace: 93,
    consistency: 84,
    wetSkill: 82,
    tireManagement: 86,
    overtaking: 86,
    defending: 88,
    adaptability: 86,
    technicalFeedback: 88,
    pressureHandling: 86,
    aggression: 86,
    teamPlay: 76,
    errorProneness: 14,
    incidentRisk: 18,
    politicalTension: 35,
    budgetCost: 155,
  },
  'driver-irvine-1999': {
    racePace: 85,
    qualifyingPace: 80,
    consistency: 88,
    wetSkill: 78,
    tireManagement: 86,
    overtaking: 80,
    defending: 84,
    adaptability: 82,
    technicalFeedback: 82,
    pressureHandling: 86,
    aggression: 78,
    teamPlay: 86,
    errorProneness: 11,
    incidentRisk: 14,
    politicalTension: 22,
    budgetCost: 135,
  },
}

const newDrivers = [
  {
    id: 'driver-stewart-1971',
    canonicalDriverId: 'jackie_stewart',
    name: 'Jackie Stewart',
    seasonYear: 1971,
    nationality: 'British',
    nationalityCode: 'GB',
    tier: 'S',
    role: 'primary',
    era: '70s',
    overall: 97,
    qualifyingPace: 94,
    racePace: 97,
    wetSkill: 91,
    tireManagement: 97,
    overtaking: 90,
    defending: 92,
    consistency: 98,
    adaptability: 96,
    technicalFeedback: 98,
    pressureHandling: 99,
    aggression: 68,
    teamPlay: 88,
    errorProneness: 5,
    incidentRisk: 7,
    politicalTension: 12,
    preferredCarTraits: '["stableRear"]',
    weakCarTraits: '["nervousRear"]',
    notes: 'Three-time champion and benchmark of precision, feedback and race craft.',
    confidence_level: 'high',
    budgetCost: 205,
  },
  {
    id: 'driver-fittipaldi-1974',
    canonicalDriverId: 'emerson_fittipaldi',
    name: 'Emerson Fittipaldi',
    seasonYear: 1974,
    nationality: 'Brazilian',
    nationalityCode: 'BR',
    tier: 'A',
    role: 'primary',
    era: '70s',
    overall: 94,
    qualifyingPace: 90,
    racePace: 94,
    wetSkill: 84,
    tireManagement: 96,
    overtaking: 88,
    defending: 90,
    consistency: 96,
    adaptability: 94,
    technicalFeedback: 95,
    pressureHandling: 96,
    aggression: 70,
    teamPlay: 90,
    errorProneness: 6,
    incidentRisk: 9,
    politicalTension: 10,
    preferredCarTraits: '["stableRear"]',
    weakCarTraits: '[]',
    notes: 'Technically gifted champion with strong race intelligence and tire care.',
    confidence_level: 'high',
    budgetCost: 180,
  },
  {
    id: 'driver-villeneuve-1979',
    canonicalDriverId: 'gilles_villeneuve',
    name: 'Gilles Villeneuve',
    seasonYear: 1979,
    nationality: 'Canadian',
    nationalityCode: 'CA',
    tier: 'A',
    role: 'primary',
    era: '70s',
    overall: 92,
    qualifyingPace: 96,
    racePace: 94,
    wetSkill: 92,
    tireManagement: 76,
    overtaking: 99,
    defending: 92,
    consistency: 78,
    adaptability: 94,
    technicalFeedback: 86,
    pressureHandling: 95,
    aggression: 100,
    teamPlay: 80,
    errorProneness: 24,
    incidentRisk: 35,
    politicalTension: 12,
    preferredCarTraits: '["strongFrontEnd"]',
    weakCarTraits: '["nervousRear"]',
    notes: 'Explosive talent, extraordinary overtaking, but with real crash risk.',
    confidence_level: 'high',
    budgetCost: 175,
  },
  {
    id: 'driver-andretti-1978',
    canonicalDriverId: 'mario_andretti',
    name: 'Mario Andretti',
    seasonYear: 1978,
    nationality: 'American',
    nationalityCode: 'US',
    tier: 'A',
    role: 'primary',
    era: '70s',
    overall: 94,
    qualifyingPace: 96,
    racePace: 95,
    wetSkill: 84,
    tireManagement: 90,
    overtaking: 92,
    defending: 90,
    consistency: 92,
    adaptability: 98,
    technicalFeedback: 94,
    pressureHandling: 95,
    aggression: 82,
    teamPlay: 86,
    errorProneness: 9,
    incidentRisk: 14,
    politicalTension: 10,
    preferredCarTraits: '["stableRear","strongFrontEnd"]',
    weakCarTraits: '[]',
    notes: 'Versatile world champion, strong in different eras and package types.',
    confidence_level: 'high',
    budgetCost: 185,
  },
  {
    id: 'driver-hill-1996',
    canonicalDriverId: 'damon_hill',
    name: 'Damon Hill',
    seasonYear: 1996,
    nationality: 'British',
    nationalityCode: 'GB',
    tier: 'A',
    role: 'primary',
    era: '90s',
    overall: 91,
    qualifyingPace: 92,
    racePace: 91,
    wetSkill: 82,
    tireManagement: 90,
    overtaking: 84,
    defending: 86,
    consistency: 93,
    adaptability: 86,
    technicalFeedback: 88,
    pressureHandling: 92,
    aggression: 70,
    teamPlay: 88,
    errorProneness: 8,
    incidentRisk: 12,
    politicalTension: 8,
    preferredCarTraits: '["stableRear"]',
    weakCarTraits: '["nervousRear"]',
    notes: 'Methodical world champion with steady pace and clean execution.',
    confidence_level: 'high',
    budgetCost: 165,
  },
  {
    id: 'driver-villeneuve-1997',
    canonicalDriverId: 'jacques_villeneuve',
    name: 'Jacques Villeneuve',
    seasonYear: 1997,
    nationality: 'Canadian',
    nationalityCode: 'CA',
    tier: 'A',
    role: 'primary',
    era: '90s',
    overall: 91,
    qualifyingPace: 94,
    racePace: 92,
    wetSkill: 80,
    tireManagement: 86,
    overtaking: 90,
    defending: 86,
    consistency: 88,
    adaptability: 88,
    technicalFeedback: 84,
    pressureHandling: 91,
    aggression: 88,
    teamPlay: 76,
    errorProneness: 13,
    incidentRisk: 18,
    politicalTension: 18,
    preferredCarTraits: '["strongFrontEnd"]',
    weakCarTraits: '["nervousRear"]',
    notes: 'Pole specialist with sharp race craft but less rounded than the all-time greats.',
    confidence_level: 'high',
    budgetCost: 165,
  },
  {
    id: 'driver-hakkinen-2000',
    canonicalDriverId: 'mika_hakkinen',
    name: 'Mika Hakkinen',
    seasonYear: 2000,
    nationality: 'Finnish',
    nationalityCode: 'FI',
    tier: 'S',
    role: 'primary',
    era: '00s',
    overall: 96,
    qualifyingPace: 98,
    racePace: 97,
    wetSkill: 84,
    tireManagement: 91,
    overtaking: 93,
    defending: 91,
    consistency: 94,
    adaptability: 92,
    technicalFeedback: 91,
    pressureHandling: 97,
    aggression: 80,
    teamPlay: 86,
    errorProneness: 8,
    incidentRisk: 11,
    politicalTension: 10,
    preferredCarTraits: '["stableRear"]',
    weakCarTraits: '[]',
    notes: 'Two-time champion and one of the cleanest high-speed qualifiers of his era.',
    confidence_level: 'high',
    budgetCost: 200,
  },
  {
    id: 'driver-montoya-2003',
    canonicalDriverId: 'juan_pablo_montoya',
    name: 'Juan Pablo Montoya',
    seasonYear: 2003,
    nationality: 'Colombian',
    nationalityCode: 'CO',
    tier: 'A',
    role: 'primary',
    era: '00s',
    overall: 93,
    qualifyingPace: 96,
    racePace: 94,
    wetSkill: 82,
    tireManagement: 82,
    overtaking: 98,
    defending: 90,
    consistency: 82,
    adaptability: 88,
    technicalFeedback: 86,
    pressureHandling: 90,
    aggression: 96,
    teamPlay: 70,
    errorProneness: 18,
    incidentRisk: 26,
    politicalTension: 32,
    preferredCarTraits: '["strongFrontEnd"]',
    weakCarTraits: '["nervousRear"]',
    notes: 'Explosive speed and overtaking, but with sharper edges than the absolute elite.',
    confidence_level: 'high',
    budgetCost: 175,
  },
]

const jsonPath = path.join(process.cwd(), 'data/curated/drivers.v1.json')
const csvPath = path.join(process.cwd(), 'data/curated/csv/drivers.v1.csv')

const drivers = JSON.parse(fs.readFileSync(jsonPath, 'utf8'))

for (const driver of drivers) {
  const update = updates[driver.id]
  if (update) {
    Object.assign(driver, update)
  }
}

for (const driver of newDrivers) {
  drivers.push(driver)
}

drivers.sort((a, b) => a.seasonYear - b.seasonYear || a.name.localeCompare(b.name) || a.id.localeCompare(b.id))

fs.writeFileSync(jsonPath, JSON.stringify(drivers, null, 2) + '\n')

const headers = [
  'id',
  'name',
  'seasonYear',
  'nationality',
  'tier',
  'role',
  'era',
  'overall',
  'qualifyingPace',
  'racePace',
  'wetSkill',
  'tireManagement',
  'overtaking',
  'defending',
  'consistency',
  'adaptability',
  'technicalFeedback',
  'pressureHandling',
  'aggression',
  'teamPlay',
  'errorProneness',
  'incidentRisk',
  'politicalTension',
  'preferredCarTraits',
  'weakCarTraits',
  'notes',
  'confidence_level',
  'budgetCost',
]

const escapeCsv = (value) => {
  const text = value === undefined || value === null ? '' : String(value)
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text
}

const csvRows = [headers.join(',')]
for (const driver of drivers) {
  csvRows.push(
    [
      driver.id,
      driver.name,
      driver.seasonYear,
      driver.nationality,
      driver.tier,
      driver.role,
      driver.era,
      driver.overall,
      driver.qualifyingPace,
      driver.racePace,
      driver.wetSkill,
      driver.tireManagement,
      driver.overtaking,
      driver.defending,
      driver.consistency,
      driver.adaptability,
      driver.technicalFeedback,
      driver.pressureHandling,
      driver.aggression,
      driver.teamPlay,
      driver.errorProneness,
      driver.incidentRisk,
      driver.politicalTension,
      driver.preferredCarTraits,
      driver.weakCarTraits,
      driver.notes,
      driver.confidence_level,
      driver.budgetCost,
    ]
      .map(escapeCsv)
      .join(',')
  )
}

fs.writeFileSync(csvPath, csvRows.join('\r\n') + '\r\n')
